# Meta information for club stuff
meta:
  semester:   fa17
  meet_day:   Wednesday
  meet_time:  7:30pm
  mtg_room:   VAB 113
  mission:    We’re on a mission to foster a hotspot for the next generation of artificial intelligence researchers and engineers at UCF.


title: Brains, Minds, & Machines @ UCF
email: bmm.ucf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We’re on a mission to foster a hotspot for the next generation of artificial intelligence researchers and engineers at UCF.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ucfsigai.github.io"

social:
  gh:     ucfsigai
  yt:     channel/UCSraILnIqJ-4oqCPp-VzxWQ
  fbg:    ucfsigai
  fbp:    ucfsigai
  slack:  sig_ai

# Build settings
future: true
markdown: kramdown
permalinks: pretty
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  hackpack:
    output: false
  post-indices:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title/
  - scope:
      path: ""
      type: "post-indices"
    values:
      layout: "semester-master"
      permalink:  /:title/
