remote_theme: "ucfsigai/global-site-theme@master"

sem: fa18
meet:
  ig:
    day: "Wed"
    time: "6:00pm"
    room: "HEC 103"
  dsg:
    day: "Mon"
    time: "6:00pm"
    room: "HEC 103"

## site title
title: SIGAI@UCF

## this should become a google group, in a few weeks (04/30/18)
email: ucfsigai@gmail.com

## SIGAI@UCF mission
description: >-
  We're forging the path to turn UCF into a hotspot for researchers and 
  engineers passionate about computational intelligence and data science.

## subpath, for the site, it's just ""
baseurl: ""
## protocol (http[s]) and tld (ucfsigai.github.io)
url: "https://ucfsigai.github.io"
social:
  github: ucfsigai
  slack:  https://ucfsigai.slack.com/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - docker-compose.yml
  - vendor/