version: "3"
services:
  site:
    command: jekyll s --incremental
    image: jekyll/jekyll:pages
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000